# Base image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Install CPU-specific PyTorch and ONNX Runtime
RUN pip install --no-cache-dir torch==2.0.1 -f https://download.pytorch.org/whl/torch_stable.html \
    && pip install --no-cache-dir onnxruntime==1.15.1

# Copy the rest of the application code
COPY . .

# Make port 5000 available to the world outside this container
EXPOSE 5000